# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fancy', '0003_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
